name: Regenerate Information Resource Registry Artifacts

# Controls when the action will run. Triggers the workflow on push
# event but only for the master branch, and specifically on the information_resource_registry.yaml
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * 1'  # at 07:00 UTC every Monday
  workflow_dispatch:
    types: trigger-build-artifacts

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: '3.11'

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget curl
          pip install poetry

      - name: Generate Information Resource Registry Artifacts
        run: |
          poetry install
          make gen-project
          make test
          make sankey
          make gendoc
          if [ $? -eq 0 ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add project/*
            git add src/*
            git add infores_catalog.yaml
            git commit -m "Regenerate artifacts from infores_catalog.yaml"
            git push
          else
            echo "'make' gen-project failed to finish successfully"
          fi